### PR TITLE
Remove unnecessary dependencies

### PR DESCRIPTION
**Pull request by fbiville**
Probably depends on https://github.com/projectriff/java-function-invoker/pull/133

These changes are necessary with the new Java invoker (there were strange classpath issues otherwise).
Maybe they also work with the current one, I have not tested that.

### CODE REVIEW

**Comment by trisberg** [comment]
If these dependencies break the new Java invoker then I think we should fix that invoker instead. It's perfectly valid to include these dependencies to be able to run the function standalone.

**Comment by fbiville** [comment]
True, let me reproduce the problem and open an issue against the Java invoker.

**Comment by fbiville** [comment]
I think the problem is that the sample currently pulls an older, incompatible version of the Spring Cloud Function deployer. We can discuss this further in the invoker [PR](https://github.com/projectriff/java-function-invoker/pull/133).

**Comment by trisberg** [comment]
Can we close this? Have you tried the latest invoker? @fbiville

**Comment by fbiville** [comment]
Yep, I saw it working.

**Pull request closed without merging**
